/** Stitch Kinetic design tokens — mirrors Flutter AppTheme */
export const AppTheme = {
  primary: '#0040E0',
  primaryDark: '#002994',
  primaryLight: '#B8C3FF',
  secondary: '#FDD400',
  secondaryDark: '#C7A500',
  tertiary: '#2ECC71',
  tertiaryDark: '#229954',
  success: '#2ECC71',
  successDark: '#229954',
  error: '#BA1A1A',
  errorDark: '#93000A',
  background: '#F6FAFE',
  surface: '#FFFFFF',
  surfaceDim: '#D6DADE',
  surfaceContainer: '#EAEEF2',
  onBackground: '#171C1F',
  onSurface: '#171C1F',
  onSurfaceVariant: '#434656',
  outline: '#C4C5D9',
  radiusSmall: 4,
  radiusDefault: 8,
  radiusMedium: 12,
  radiusLarge: 16,
  radiusXLarge: 24,
  radiusFull: 9999,
  maxContentWidth: 650,
} as const;

export const CEFR_UNITS = [
  {
    title: 'Unidad 1: Básico Principiante A1',
    desc: 'Verbos de uso diario (to be, to have, to do, to go...)',
    level: 'a1',
    verbsCount: 60,
    color: AppTheme.primary,
    icon: 'star',
  },
  {
    title: 'Unidad 2: Básico Elemental A2',
    desc: 'Verbos cotidianos (to speak, to learn, to buy, to choose...)',
    level: 'a2',
    verbsCount: 60,
    color: AppTheme.secondary,
    icon: 'flash',
  },
  {
    title: 'Unidad 3: Intermedio B1',
    desc: 'Verbos de comunicación general (to build, to spend, to agree...)',
    level: 'b1',
    verbsCount: 60,
    color: AppTheme.tertiary,
    icon: 'trophy',
  },
  {
    title: 'Unidad 4: Intermedio Alto B2',
    desc: 'Verbos de fluidez y precisión (to achieve, to establish, to reduce...)',
    level: 'b2',
    verbsCount: 60,
    color: '#9B59B6',
    icon: 'analytics',
  },
  {
    title: 'Unidad 5: Avanzado C1',
    desc: 'Verbos profesionales y académicos (to foster, to leverage, to tackle...)',
    level: 'c1',
    verbsCount: 60,
    color: AppTheme.error,
    icon: 'diamond',
  },
  {
    title: 'Unidad 6: Experto C2',
    desc: 'Verbos de maestría y retórica (to excel, to elucidate, to corroborate...)',
    level: 'c2',
    verbsCount: 60,
    color: '#E67E22',
    icon: 'ribbon',
  },
] as const;

export const AVATARS = [
  { name: 'Miri Feliz', path: 'assets/images/mascot_happy.png' },
  { name: 'Miri Celebrando', path: 'assets/images/mascot_celebrating.png' },
  { name: 'Miri Triste', path: 'assets/images/mascot_sad.png' },
] as const;
